export { default as AboutUs } from './AboutUs'
export { default as ContactUs } from './ContactUs'
export { default as FAQ } from './FAQ'
export { default as Process } from './Process'
export { default as Services } from './Services'
export { default as Testimonials } from './Testimonials'
export { default as Values } from './Values'
export { default as Hero } from './Hero'
